### ISSUE TITLE
Incorrect include paths in the file 'vscp_evt_information.c' (compile error)

### ISSUE THREAD

**Issue by michpro** [BlueAndi/vscp-arduino#10]
In the file 'vscp_evt_information.c' is:
```
#include "vscp_evt_information.h"
#include "vscp_core.h"
#include "vscp_class_l1.h"
#include "vscp_type_information.h"
```
, and should be:
```
#include "vscp_evt_information.h"
#include "../core/vscp_core.h"
#include "../core/vscp_class_l1.h"
#include "../core/vscp_type_information.h"
```

**Comment by BlueAndi** [comment]
Thanks, I missed that somehow. The problem is always that changes from vscp-framework needs additional changes for Arduino, because they still doesn't support to set include search path. Now I added a CI workflow, which should help next time. :-)
