### ISSUE TITLE
[not an issue, just discussion] Any advice on at90can* support or example?

### ISSUE THREAD

**Issue by datenheim** [BlueAndi/vscp-arduino#3]
Hi Andreas, some years ago I was a little more active on vscp and we had contact then.

Now it's time to revive an old firmware made with WinAVR back than with your nice Arduino library.
Since the MegaCore provides support for AT90CAN devices, I wondered what is left to do to get it going on these devices?
Is it as easy as copying some lines over from Akhe's vscp-firmware/avr/common/ to transportRead() and transportWrite()?

Any Advice is welcome :)
If I get it going, I would supply my example (platformio project) as addition here...

**Comment by BlueAndi** [comment]
Hi Stefan, nice to hear you again.

As I see, you may only need the CAN driver. Don't know whether in the meantime there is one available via platformio lib for any AT90CAN.

In the vscp-framework I created years ago a example for AT90CAN32: https://github.com/BlueAndi/vscp-framework/tree/master/examples/avr/at90can

If you follow the generic example in the vscp-arduino + adapting the transportRead/Write functions like here:
https://github.com/BlueAndi/vscp-framework/blob/master/examples/avr/at90can/vscp_user/vscp_tp_adapter.c
it should not be a big deal.

I guess you can use the drivers from here, depended on the device type:
https://github.com/grodansparadis/vscp-firmware/tree/master/avr/common
