### ISSUE TITLE
Compilation errors due to missing 'extern “C”' in *.h files in events directory.

### ISSUE THREAD

**Issue by michpro** [BlueAndi/vscp-arduino#5]
Since Arduino code is assumed to be written (and compiled) in c++, the lack of 'extern “C”' in the *.h headers in the functions in the events directory causes Name Mangling which leads to compilation errors (inability to find the object when linking).

**Comment by BlueAndi** [comment]
Could it be that in earlier days the .c files were compiled as C++, because it was working on my side without issue.
But you are right, will add them.
